[package]
name = "mm-ci-test-simple-node"
version = "2.0.0"
authors = ["Benjamin Kampmann <ben@gnunicorn.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
