# This is a basic workflow to help you get started with Actions

name: check for semver

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ stable ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
      with:
        ref: stable
        path: stable
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        path: new
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          override: trues
    - name: Install master toolchain
      run: |
        cargo +nightly install rustup-toolchain-install-master
        rustup-toolchain-install-master eeaf497b2a6bc065874e3d3367b1f3023c5bb3d3 -f -n master -c rustc-dev -c llvm-tools
    - name: Install semverver
      run: cargo +master install --git https://github.com/rust-dev-tools/rust-semverver

    - name: Check semver compability
      run: |
          members=("primitives/api" "client/client" "frame/runtime" "bin/binary" "examples/simple-node" "tests/chaosneet")

          for member in ${members[@]}; do
              cargo semver --stable-path "stable/${member}" --current-path "new/${member}"
          done
