# This is a basic workflow to help you get started with Actions

name: check for semver

env:
  NIGHTLY_VERSION: nightly-2020-06-02

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: [ stable ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    - uses: actions/cache@v2
      with:
        path: |
          ~/.rustup/
          ~/.cargo/registry
          ~/.cargo/git
          ~/.cargo/bin
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - uses: actions/checkout@v2
      with:
        ref: stable
        path: stable
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        path: new
    - name: Install nightly
      uses: actions-rs/toolchain@v1
      with:
          toolchain: ${{ env.NIGHTLY_VERSION }}
          override: true
          components: rustc-dev, llvm-tools-preview
    # - name: Install master toolchain
    #   run: |
    #     cargo +nightly install rustup-toolchain-install-master
    #     rustup-toolchain-install-master eeaf497b2a6bc065874e3d3367b1f3023c5bb3d3 -f -n master -c rustc-dev -c llvm-tools
    - name: Install semverver
      run: cargo +${{ env.NIGHTLY_VERSION }} install --git https://github.com/rust-dev-tools/rust-semverver

    - name: Check semver compability
      run: |
          members=("client/client" ) # "frame/runtime" "examples/simple-node" "tests/chaosneet")

          for member in ${members[@]}; do
              cargo +${{ env.NIGHTLY_VERSION }} semver --stable-path "$GITHUB_WORKSPACE/stable/${member}/Cargo.toml" --current-path "$GITHUB_WORKSPACE/new/${member}/Cargo.toml"
          done
